### ISSUE TITLE
Invalid stop times

### ISSUE THREAD

**Issue by jbruechert** [MKuranowski/PKPIntercityGTFS#1]
Thanks for providing this GTFS feed!

Since today, gtfsclean / gtfstidy complain about
```
stop_times.txt:13 - max representable time is '127:59:59', found '149:09:00' for field arrival_time
```
when processing this feed.

This seems to be correct judging from the GTFS validator: https://gtfs-validator-results.mobilitydata.org/39275a61-e674-4da2-8be3-b95ef5277668/report.html

**Comment by MKuranowski** [comment]
This seems to no longer be an issue in the latest version – I presume this was due to some mistake in the source data.
